name: Keep Backend Alive

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: |
          curl -f https://portfolio-tagda.onrender.com/health || echo "Backend is sleeping, this is normal"
        timeout-minutes: 1 